const state={data:window.SPLINTERLANDS_TOURNAMENT_DATA||{tournaments:[]},selectedId:null,view:"bracket",round:null,group:"all",revealNames:false,revealScores:false,revealWinners:false,statusFilters:new Set(["completed","in_progress","upcoming"]),formatFilter:"any"};
const els={tournamentSelect:document.querySelector("#tournamentSelect"),tournamentIdInput:document.querySelector("#tournamentIdInput"),loadTournamentButton:document.querySelector("#loadTournamentButton"),refreshListsButton:document.querySelector("#refreshListsButton"),roundSelect:document.querySelector("#roundSelect"),groupSelect:document.querySelector("#groupSelect"),statusBox:document.querySelector("#statusBox"),tournamentKicker:document.querySelector("#tournamentKicker"),tournamentTitle:document.querySelector("#tournamentTitle"),metaStrip:document.querySelector("#metaStrip"),heroBadge:document.querySelector("#heroBadge"),roundKicker:document.querySelector("#roundKicker"),roundTitle:document.querySelector("#roundTitle"),roundStats:document.querySelector("#roundStats"),matchBoard:document.querySelector("#matchBoard"),standingsTable:document.querySelector("#standingsTable"),payoutList:document.querySelector("#payoutList"),talkingPoints:document.querySelector("#talkingPoints"),featuredMatch:document.querySelector("#featuredMatch"),streamModeToggle:document.querySelector("#streamModeToggle"),exitStreamModeButton:document.querySelector("#exitStreamModeButton"),statusFilters:document.querySelectorAll(".status-filter"),formatFilter:document.querySelector("#formatFilter")};
const apiBase="https://game-api.splinterlands.com";
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c])}
function fmtDate(v){return v?new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"Date TBC"}
function statusLabel(s){return({0:"Created",1:"Live",2:"Completed",3:"Cancelled"})[s]||`Status ${s??"unknown"}`}
function bucket(t){if(t.list_label==="Upcoming")return"upcoming";if(t.list_label==="In progress")return"in_progress";if(t.list_label==="Completed")return"completed";if(Number(t.status)===2)return"completed";if(Number(t.status)===1)return"in_progress";return"upcoming"}
function formatLabel(f){return f?String(f).split("_").map(p=>p.charAt(0).toUpperCase()+p.slice(1)).join(" "):"Unknown format"}
function rounds(t){const r=[...new Set((t.matches||[]).map(m=>m.round))].sort((a,b)=>Number(a)-Number(b));return r.length?r:(t.rounds||[]).map(r=>r.round)}
function currentTournament(){return state.data.tournaments.find(t=>t.id===state.selectedId)||state.data.tournaments[0]}
function setStatus(m){els.statusBox.textContent=m}
function playerLabel(n,visible=true){return visible&&state.revealNames?esc(n||"BYE"):`<span class="hidden-token">${esc(n||"Hidden player")}</span>`}
function scoreLabel(s,visible=true){return visible&&state.revealScores?esc(s??"-"):'<span class="hidden-token">0</span>'}
function winnerClass(m,p,visible=true){return visible&&state.revealWinners&&m.winner===p?" is-winner":""}
function battleUrl(q){return`https://splinterlands.com/battle/${encodeURIComponent(q)}`}
function battleLinks(m){return m.battle_links||[]}
function simplifyTournament(d){return{id:d.id,name:d.name,start_date:d.start_date,status:d.status,format:d.format,sponsor_name:d.sponsor_name,entry_fee:d.entry_fee,total_prizes_usd:d.total_prizes_usd||d.data?.total_prizes_usd,num_players:d.num_players||d.players?.length||0,rounds:d.rounds||[],players:d.players||[],prizes:(d.data?.prizes?.payouts||[]).map(p=>{const place=p.start_place===p.end_place?`Place ${p.start_place}`:`Places ${p.start_place}-${p.end_place}`;const items=(p.items||[]).map(i=>`${i.qty} ${i.type}${i.text?` ${i.text}`:""}`).join(", ");return`${place}: ${items}`}),matches:[]}}
async function fetchJson(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
async function loadTournamentFromApi(id){setStatus(`Loading ${id} from Splinterlands API...`);const detail=await fetchJson(`${apiBase}/tournaments/find?id=${encodeURIComponent(id)}`);const t=simplifyTournament(detail);t.current_round=detail.current_round;for(const round of detail.rounds||[]){const groups=Number(round.num_swiss_groups)>0?Array.from({length:Number(round.num_swiss_groups)},(_,i)=>i+1):[null];for(const group of groups){const suffix=group===null?"":`&swiss_group=${group}`;const matches=await fetchJson(`${apiBase}/tournaments/battles?id=${encodeURIComponent(id)}&round=${round.round}${suffix}`);t.matches.push(...matches.map(m=>({id:m.id,round:m.round,index:m.index,best_of:m.best_of,swiss_group:m.swiss_group||null,player_1:m.player_1,player_2:m.player_2,player_1_wins:m.player_1_wins,player_2_wins:m.player_2_wins,winner:m.winner,battles_count:m.battles?.length||0,battle_links:(m.battles||[]).flatMap((b,i)=>{const q=b.battle_queue_id_1||b.battle_queue_id_2;return q?[{label:`Battle ${i+1}`,queue_id:q,url:battleUrl(q)}]:[]})})))}}state.data.tournaments=[t,...state.data.tournaments.filter(x=>x.id!==t.id)];state.selectedId=t.id;state.round=null;state.group="all";render()}
async function refreshApiLists(){setStatus("Refreshing tournament lists...");let added=0;for(const [endpoint,label]of[["upcoming","Upcoming"],["in_progress","In progress"],["completed","Completed"]]){const list=await fetchJson(`${apiBase}/tournaments/${endpoint}`);for(const item of Array.isArray(list)?list:[]){const existing=state.data.tournaments.find(t=>t.id===item.id);if(existing)Object.assign(existing,{...simplifyTournament(item),matches:existing.matches||[],list_label:label,current_round:item.current_round});else{state.data.tournaments.push({...simplifyTournament(item),list_label:label,current_round:item.current_round});added++}}}render();setStatus(`API lists refreshed. Added ${added} tournaments. Select one to load its full bracket.`)}
function renderPicker(){const formats=[...new Set(state.data.tournaments.map(t=>t.format).filter(Boolean))].sort((a,b)=>formatLabel(a).localeCompare(formatLabel(b)));els.formatFilter.innerHTML=['<option value="any">Any format</option>',...formats.map(f=>`<option value="${esc(f)}">${esc(formatLabel(f))}</option>`)].join("");els.formatFilter.value=formats.includes(state.formatFilter)?state.formatFilter:"any";state.formatFilter=els.formatFilter.value;const list=[...state.data.tournaments].filter(t=>state.statusFilters.has(bucket(t))).filter(t=>state.formatFilter==="any"||t.format===state.formatFilter).sort((a,b)=>new Date(b.start_date||0)-new Date(a.start_date||0));if(!list.some(t=>t.id===state.selectedId)){state.selectedId=list[0]?.id||null;state.round=null;state.group="all"}els.tournamentSelect.innerHTML=list.map(t=>`<option value="${esc(t.id)}">${esc(statusLabel(t.status))}: ${esc(t.name)}</option>`).join("");els.tournamentSelect.value=state.selectedId||""}
function renderRoundControls(t){const rs=rounds(t);if(!state.round||!rs.includes(Number(state.round)))state.round=rs[0]??1;const prefix=t.format==="single_elimination"?"Reveal through round":"Round";els.roundSelect.innerHTML=rs.map(r=>`<option value="${esc(r)}">${prefix} ${esc(r)}</option>`).join("");els.roundSelect.value=state.round;const groups=[...new Set((t.matches||[]).filter(m=>String(m.round)===String(state.round)).map(m=>m.swiss_group||"none"))].sort((a,b)=>Number(a)-Number(b));els.groupSelect.innerHTML=['<option value="all">All groups</option>',...groups.map(g=>`<option value="${esc(g)}">${g==="none"?"Main bracket":`Group ${esc(g)}`}</option>`)].join("");if(![...groups.map(String),"all"].includes(String(state.group)))state.group="all";els.groupSelect.value=state.group}
function renderHero(t){els.tournamentKicker.textContent=`${statusLabel(t.status)} ${t.format||"tournament"}`;els.tournamentTitle.textContent=t.name||"Untitled tournament";els.heroBadge.textContent=state.view;els.metaStrip.innerHTML=[fmtDate(t.start_date),`${t.num_players||0} players`,t.entry_fee||"Entry fee unknown",t.total_prizes_usd?`$${Number(t.total_prizes_usd).toFixed(0)} prizes`:"Prize info pending",t.sponsor_name||"Community event"].map(x=>`<span class="pill">${esc(x)}</span>`).join("")}
function currentMatches(t){return(t.matches||[]).filter(m=>String(m.round)===String(state.round)&&(state.group==="all"||String(m.swiss_group||"none")===String(state.group)))}
function renderMatchCard(m,visible){const links=battleLinks(m);return`<article class="match-card"><div class="match-head"><span>Match ${esc(Number(m.index??0)+1)}</span><span>${esc(m.best_of?`Best of ${m.best_of}`:"Match")}</span></div><div class="player-row${winnerClass(m,m.player_1,visible)}"><div class="player-name">${playerLabel(m.player_1,visible)}</div><div class="score">${scoreLabel(m.player_1_wins,visible)}</div></div><div class="player-row${winnerClass(m,m.player_2,visible)}"><div class="player-name">${playerLabel(m.player_2,visible)}</div><div class="score">${scoreLabel(m.player_2_wins,visible)}</div></div>${visible&&state.revealScores&&links.length?`<div class="match-links">${links.map(l=>`<a href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">${esc(l.label)}</a>`).join("")}</div>`:""}</article>`}
function roundName(r,rs){const i=rs.findIndex(x=>String(x)===String(r));const left=rs.length-i;if(left===1)return"Final";if(left===2)return"Semi Final";if(left===3)return"Quarter Final";return`Round ${r}`}
function matchPlayers(m){return[m.player_1,m.player_2].filter(Boolean)}
function orderedRounds(matches,rs){const by=new Map(rs.map(r=>[String(r),[]]));for(const m of matches){const k=String(m.round);if(!by.has(k))by.set(k,[]);by.get(k).push(m)}const out=new Map();let prev=new Map();for(const r of rs){const items=[...(by.get(String(r))||[])].map(m=>{const src=matchPlayers(m).map(p=>prev.get(p)).filter(s=>s!==undefined);return{m,slot:src.length?Math.min(...src):Number(m.index??0)}}).sort((a,b)=>a.slot-b.slot||Number(a.m.index??0)-Number(b.m.index??0));out.set(String(r),items.map(x=>x.m));prev=new Map();items.forEach((x,i)=>{for(const p of matchPlayers(x.m))prev.set(p,i);if(x.m.winner)prev.set(x.m.winner,i)})}return out}
function renderBracket(t){if(t.format==="single_elimination")return renderSingle(t);const matches=currentMatches(t);const done=matches.filter(m=>m.winner).length;els.roundKicker.textContent=state.group==="all"?"All groups":`Group ${state.group}`;els.roundTitle.textContent=`Round ${state.round} Matchups`;els.roundStats.innerHTML=[`${matches.length} matches`,`${done} decided`,`${matches.reduce((s,m)=>s+(m.battles_count||0),0)} battles`].map(x=>`<span class="pill">${esc(x)}</span>`).join("");els.matchBoard.className="match-board";els.matchBoard.innerHTML=matches.length?matches.map(m=>renderMatchCard(m,true)).join(""):'<div class="status-box">No matchup data loaded for this round yet.</div>'}
function renderSingle(t){const rs=rounds(t);const selected=Number(state.round||rs[0]||1);const matches=(t.matches||[]).filter(m=>state.group==="all"||String(m.swiss_group||"none")===String(state.group));const ordered=orderedRounds(matches,rs);els.roundKicker.textContent="Single elimination bracket";els.roundTitle.textContent=`Reveal Through Round ${selected}`;els.roundStats.innerHTML=[`${matches.length} matches`,`${rs.length} rounds`,`${matches.filter(m=>m.winner).length} decided`].map(x=>`<span class="pill">${esc(x)}</span>`).join("");els.matchBoard.className=matches.length?"single-bracket":"match-board";els.matchBoard.innerHTML=matches.length?rs.map(r=>{const visible=Number(r)<=selected;const ms=ordered.get(String(r))||[];return`<section class="bracket-round${visible?" is-revealed":" is-locked"}"><div class="bracket-round-title"><span>${esc(roundName(r,rs))}</span><strong>${ms.length} matches</strong></div><div class="bracket-round-stack">${ms.map(m=>renderMatchCard(m,visible)).join("")}</div></section>`}).join(""):'<div class="status-box">No bracket data loaded. Refresh lists, select the tournament, or paste a tournament ID.</div>'}
function renderStandings(t){const players=[...(t.players||[])].sort((a,b)=>(Number(a.finish||9999)-Number(b.finish||9999))||(Number(b.wins||0)-Number(a.wins||0))).slice(0,48);els.standingsTable.innerHTML=['<div class="table-row header"><span>Place</span><span>Player</span><span>Wins</span><span>Losses</span></div>',...players.map((p,i)=>`<div class="table-row"><span>${esc(p.finish||i+1)}</span><strong class="${state.revealNames?"":"hidden-token"}">${esc(p.player)}</strong><span>${esc(p.wins??0)}</span><span>${esc(p.losses??0)}</span></div>`)].join("");els.payoutList.innerHTML=(t.prizes||[]).length?t.prizes.map(p=>`<div class="payout-row">${esc(p)}</div>`).join(""):'<div class="payout-row">No payout data available.</div>'}
function renderHost(t){const top=[...(t.players||[])].filter(p=>p.finish).sort((a,b)=>Number(a.finish)-Number(b.finish)).slice(0,4).map(p=>p.player).join(", ");const matches=currentMatches(t);const f=matches.find(m=>m.winner)||matches[0];els.talkingPoints.innerHTML=[`${t.name} started ${fmtDate(t.start_date)}.`,`${t.num_players||0} players entered; format is ${t.format||"unknown"}.`,top?`Current top finishers: ${top}.`:"Final standings are not available yet.",matches.length?`Round ${state.round} has ${matches.length} matchups in this view.`:"No cached matchups for this round yet."].map(p=>`<div class="talk-row">${esc(p)}</div>`).join("");els.featuredMatch.innerHTML=f?`<div class="featured-card"><div class="featured-versus"><span>${playerLabel(f.player_1)}</span><span>vs</span><span>${playerLabel(f.player_2)}</span></div><div class="meta-strip"><span class="pill">${esc(f.winner?`Winner: ${state.revealWinners?f.winner:"hidden"}`:"Undecided")}</span><span class="pill">${esc(f.battles_count||0)} battles</span></div></div>`:'<div class="featured-card">No featured match available.</div>'}
function renderViews(){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("is-active",v.id===`${state.view}View`));document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("is-active",b.dataset.view===state.view))}
function render(){renderPicker();const t=currentTournament();if(!t){setStatus("No tournaments match the selected filters.");els.tournamentTitle.textContent="No tournaments selected";els.matchBoard.innerHTML="";return}state.selectedId=t.id;renderRoundControls(t);renderHero(t);renderBracket(t);renderStandings(t);renderHost(t);renderViews();setStatus(`${t.matches?.length||0} matchups loaded for ${t.name}.`)}
els.tournamentSelect.addEventListener("change",e=>{state.selectedId=e.target.value;state.round=null;state.group="all";const t=currentTournament();if(t&&(!t.rounds?.length||(!t.matches?.length&&Number(t.current_round||0)>0)))loadTournamentFromApi(e.target.value).catch(err=>{setStatus(`Could not load tournament detail: ${err.message}`);render()});else render()});
els.roundSelect.addEventListener("change",e=>{state.round=e.target.value;state.group="all";render()});els.groupSelect.addEventListener("change",e=>{state.group=e.target.value;render()});document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>{state.view=b.dataset.view;render()}));document.querySelector("#revealNamesButton").addEventListener("click",()=>{state.revealNames=!state.revealNames;render()});document.querySelector("#revealScoresButton").addEventListener("click",()=>{state.revealScores=!state.revealScores;render()});document.querySelector("#revealWinnersButton").addEventListener("click",()=>{state.revealWinners=!state.revealWinners;render()});document.querySelector("#revealAllButton").addEventListener("click",()=>{state.revealNames=true;state.revealScores=true;state.revealWinners=true;render()});document.querySelector("#hideAllButton").addEventListener("click",()=>{state.revealNames=false;state.revealScores=false;state.revealWinners=false;render()});els.streamModeToggle.addEventListener("change",e=>document.body.classList.toggle("stream-clean",e.target.checked));els.exitStreamModeButton.addEventListener("click",()=>{els.streamModeToggle.checked=false;document.body.classList.remove("stream-clean")});els.statusFilters.forEach(i=>i.addEventListener("change",()=>{state.statusFilters=new Set([...els.statusFilters].filter(x=>x.checked).map(x=>x.value));render()}));els.formatFilter.addEventListener("change",e=>{state.formatFilter=e.target.value;render()});els.loadTournamentButton.addEventListener("click",()=>{const id=els.tournamentIdInput.value.trim();if(id)loadTournamentFromApi(id).catch(e=>setStatus(`Could not load from API: ${e.message}`))});els.refreshListsButton.addEventListener("click",()=>refreshApiLists().catch(e=>setStatus(`Could not refresh API lists: ${e.message}`)));render();
